services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoudagor-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - .env
